import Head from "next/head";
import Hero from "../components/Hero";
import Speakers from "@/components/Speakers";
import Sponsors from "@/components/Sponsors";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>TEDxBITSGoa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Speakers />
      <Sponsors />
      <Footer />
    </>
  );
}
